/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as RelatoriosIdRouteImport } from './routes/relatorios.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosIdRoute = RelatoriosIdRouteImport.update({
  id: '/relatorios/$id',
  path: '/relatorios/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/relatorios/$id': typeof RelatoriosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/relatorios/$id': typeof RelatoriosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/relatorios/$id': typeof RelatoriosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/auditoria' | '/monitoramento' | '/relatorios/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/auditoria' | '/monitoramento' | '/relatorios/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auditoria'
    | '/monitoramento'
    | '/relatorios/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditoriaRoute: typeof AuditoriaRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  RelatoriosIdRoute: typeof RelatoriosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/$id': {
      id: '/relatorios/$id'
      path: '/relatorios/$id'
      fullPath: '/relatorios/$id'
      preLoaderRoute: typeof RelatoriosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditoriaRoute: AuditoriaRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  RelatoriosIdRoute: RelatoriosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
