"""Cria tabelas iniciais

Revision ID: c64271b9ba2c
Revises: 
Create Date: 2026-09-13 10:50:01.111060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64271b9ba2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('local_instalacao', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rtsp_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'MANUTENCAO', name='camerastatus'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_tenant_id'), 'cameras', ['tenant_id'], unique=False)
    op.create_table('pessoas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('atributos', sa.JSON(), nullable=True),
    sa.Column('face_confianca', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoas_tenant_id'), 'pessoas', ['tenant_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('OPERADOR', 'ADMINISTRADOR', name='userrole'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_tenant_id'), 'usuarios', ['tenant_id'], unique=False)
    op.create_table('veiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=16), nullable=False),
    sa.Column('cor', sa.String(length=64), nullable=True),
    sa.Column('modelo', sa.String(length=128), nullable=True),
    sa.Column('status_restricao', sa.Enum('NENHUMA', 'RESTRITO', 'NAO_VERIFICADO', name='restricaostatus'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_placa'), 'veiculos', ['placa'], unique=False)
    op.create_index(op.f('ix_veiculos_tenant_id'), 'veiculos', ['tenant_id'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('alvo_id', sa.UUID(), nullable=True),
    sa.Column('tipo_evento', sa.Enum('PESSOA_DETECTADA', 'VEICULO_DETECTADO', 'ALERTA_CONFIGURADO', name='tipoevento'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('clip_url', sa.String(length=1024), nullable=True),
    sa.Column('confianca_media', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_tenant_id'), 'eventos', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_eventos_timestamp'), 'eventos', ['timestamp'], unique=False)
    op.create_table('investigacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('criterios_busca_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', name='investigacaostatus'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('fechado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigacoes_tenant_id'), 'investigacoes', ['tenant_id'], unique=False)
    op.create_table('logs_auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('acao', sa.String(length=128), nullable=False),
    sa.Column('entidade_afetada', sa.String(length=255), nullable=True),
    sa.Column('ip_origem', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_auditoria_tenant_id'), 'logs_auditoria', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_logs_auditoria_timestamp'), 'logs_auditoria', ['timestamp'], unique=False)
    op.create_table('deteccoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('PESSOA', 'VEICULO', name='tipodeteccao'), nullable=False),
    sa.Column('bbox_json', sa.JSON(), nullable=True),
    sa.Column('confianca', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deteccoes_tenant_id'), 'deteccoes', ['tenant_id'], unique=False)
    op.create_table('investigacao_eventos',
    sa.Column('investigacao_id', sa.UUID(), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['investigacao_id'], ['investigacoes.id'], ),
    sa.PrimaryKeyConstraint('investigacao_id', 'evento_id')
    )
    op.create_table('relatorios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('investigacao_id', sa.UUID(), nullable=False),
    sa.Column('pdf_url', sa.String(length=1024), nullable=True),
    sa.Column('gerado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigacao_id'], ['investigacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relatorios_tenant_id'), 'relatorios', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relatorios_tenant_id'), table_name='relatorios')
    op.drop_table('relatorios')
    op.drop_table('investigacao_eventos')
    op.drop_index(op.f('ix_deteccoes_tenant_id'), table_name='deteccoes')
    op.drop_table('deteccoes')
    op.drop_index(op.f('ix_logs_auditoria_timestamp'), table_name='logs_auditoria')
    op.drop_index(op.f('ix_logs_auditoria_tenant_id'), table_name='logs_auditoria')
    op.drop_table('logs_auditoria')
    op.drop_index(op.f('ix_investigacoes_tenant_id'), table_name='investigacoes')
    op.drop_table('investigacoes')
    op.drop_index(op.f('ix_eventos_timestamp'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_tenant_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_veiculos_tenant_id'), table_name='veiculos')
    op.drop_index(op.f('ix_veiculos_placa'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_usuarios_tenant_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_pessoas_tenant_id'), table_name='pessoas')
    op.drop_table('pessoas')
    op.drop_index(op.f('ix_cameras_tenant_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
